name: Update recent activity

on:
  schedule:
    - cron: "17 */6 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/update-activity.yml"

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
